monitoring_mail.settings:
  type: config_object
  label: 'Monitoring mail settings'
  mapping:
    mail:
      type: email
      label: 'Mail recipient'
    severities:
      type: sequence
      label: 'Mail status options'
      sequence:
        type: string
        label: 'Mail status option'